backend:
  name: github
  repo: siq-s/quiz-club  # あなたのリポジトリ名に合わせました
  branch: main
  base_url: https://cms-proxy-alpha.vercel.app
  site_domain: quiz-club-hh1d48qhy-siqs-projects.vercel.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "ページ編集"
    files:
      - label: "トップページ"
        name: "index"
        file: "data/index.json"
        fields:
          - {label: "メインタイトル", name: "site_title", widget: "string"}
          - {label: "サブタイトル", name: "site_subtitle", widget: "string"}
          - {label: "ロゴ画像", name: "logo_image", widget: "image", required: false}
          - {label: "活動紹介文", name: "intro_text", widget: "text"}
