backend:
  name: git-gateway
  repo: ruuku4616-creator/quiz_club
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "ページ編集"
    files:
      - label: "トップページ"
        name: "index"
        file: "data/index.json"
        fields:
         - { name: "site_title_en", label: "ヘッダー名 (英語)", widget: "string", default: "Shibaura Institute of Quiz" }
         - { name: "site_title_jp", label: "トップページ見出し (日本語)", widget: "string", default: "芝浦工業大学柏高等学校クイズ研究会" }
         - { name: "site_subtitle", label: "サブタイトル", widget: "string" }
         - { name: "intro_text", label: "紹介文", widget: "text" }
         - { name: "logo_image", label: "ロゴ画像", widget: "image", required: false }

  - name: "active"
    label: "活動報告"
    folder: "data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "投稿者名", name: "author", widget: "string", required: false} # ★追加（任意入力にしています）
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "アイキャッチ画像", name: "thumbnail", widget: "image", required: false}
      - {label: "本文", name: "body", widget: "markdown"}

  - name: "quiz"
    label: "SIQ今日の一問"
    folder: "data/quiz"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル（管理用）", name: "title", widget: "string"}
      - {label: "問題文と回答", name: "body", widget: "text"}

  - name: "event"
    label: "芝柏杯 特設ページ管理"
    files:
      - label: "大会基本情報"
        name: "info"
        file: "data/event.json"
        fields:
          - {label: "大会名", name: "event_title", widget: "string"}
          - {label: "キャッチコピー", name: "event_copy", widget: "text"}
          - {label: "開催日", name: "event_date", widget: "string"}
          - {label: "会場", name: "event_place", widget: "string"}
          - {label: "定員", name: "event_capacity", widget: "string"}
          - {label: "参加費", name: "event_fee", widget: "string"}
          - {label: "エントリーURL", name: "entry_url", widget: "string", required: false}
          - {label: "大会ルール・詳細", name: "event_details", widget: "markdown"}

  - name: "members_blog"
    label: "部員ブログ"
    folder: "data/members_blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{author}}-{{title}}" # ファイル名に投稿者名を含める
    fields:
      - {label: "投稿者名", name: "author", widget: "string"} # ★ここを追加
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "投稿日", name: "date", widget: "datetime"}
      - {label: "本文", name: "body", widget: "markdown"}


