backend:
  name: git-gateway
  repo: ruuku4616-creator/quiz_club
  branch: main
  
media_folder: "images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "ページ編集"
    files:
      - label: "トップページ"
        name: "index"
        file: "data/index.json"
        fields:
          - {label: "サイトタイトル", name: "site_title", widget: "string"}
          - {label: "キャッチコピー", name: "site_subtitle", widget: "string"}
          - {label: "活動紹介文", name: "intro_text", widget: "text"}
          - {label: "ロゴ画像", name: "logo_image", widget: "image", required: false}

  - name: "blog"
    label: "活動報告"
    folder: "data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "アイキャッチ画像", name: "thumbnail", widget: "image", required: false}
      - {label: "本文", name: "body", widget: "markdown"}











